events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass         http://app:5000;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_read_timeout 60s;
        }

        location /analytics {
            return 301 http://localhost:3002;
        }

        location /admin {
            return 301 http://localhost:5050;
        }
    }
}
